test: Thread.c Init.c Scheduler.c TestCase1.c TestCase2.c TestCase3.c TestCase4.c TestMain.c doubleLinked.c App.c
	gcc -o test Thread.c Init.c Scheduler.c TestCase1.c TestCase2.c TestCase3.c TestCase4.c TestMain.c doubleLinked.c App.c

clean: 
	rm -f Thread.o Init.o Scheduler.o TestCase1.o TestCase2.o TestCase3.o TestCase4.o TestMain.o doubleLinked.o App.o


